---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-pass-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-demo/backstage-pass-gitops